import asyncio
import logging
from google.adk.runners import Runner
from google.adk.sessions.database_session_service import DatabaseSessionService
from google.genai import types

from src.config import get_settings
from src.agent.orchestrator_agent import orchestrator_agent

settings = get_settings()
logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)
app_name = settings.app_name
user_id = settings.user_id
session_id = "agentic_rag_session_123"
database_url = settings.database_url
db_type = settings.db_type


session_service = DatabaseSessionService(database_url)

async def setup_session_and_runner():
    # Initialize the observability schema
    initial_state = {
        "agent_flow": [],
        "agent_outputs": {},
        "agent_start_times": {},
        "agent_latencies": {},
        "tools_called": [],
        "retrieved_sources": []
    }
    try:
        session = await session_service.create_session(app_name=app_name, user_id=user_id, session_id=session_id,state=initial_state)
    except Exception as e:
        session = await session_service.get_session(app_name=app_name, user_id=user_id, session_id=session_id)
    
    runner = Runner(agent=orchestrator_agent, app_name=app_name, session_service=session_service)
    return runner, session.id


async def call_agent_with_observability(query):
    runner, active_session_id = await setup_session_and_runner()
    content = types.Content(role='user', parts=[types.Part(text=query)])
    
    print(f"\n{'='*20} AGENTIC RUN: {active_session_id} {'='*20}\n")

    ans = "No response generated by the agent."
    
    events = runner.run_async(
        user_id=user_id, 
        session_id=active_session_id, 
        new_message=content
    )

    async for event in events:
        # We can still print tool calls live from the event stream
        if event.get_function_calls():
            for call in event.get_function_calls():
                print(f"🛠  [Tool] {event.author} calling: {call.name}")

        if event.is_final_response() and event.content and event.content.parts:
            final_response_text = event.content.parts[0].text.strip()
            if "APPROVED" not in final_response_text:
                ans = final_response_text
            print(f"\n\033[95mFINAL ANSWER:\033[0m\n {final_response_text}")

    # --- FINAL OBSERVABILITY REPORT ---
    # Fetch the finalized state from the database
    final_session = await runner.session_service.get_session(app_name =app_name, user_id=user_id, session_id=active_session_id)
    state = final_session.state

    print("\n" + "📊" * 5 + " OBSERVABILITY DASHBOARD " + "📊" * 5)
    print(f"Flow: {' ➔ '.join(state.get('agent_flow', []))}")
    
    print("\nLatency per Agent:")
    for agent, sec in state.get('agent_latencies', {}).items():
        print(f" - {agent}: {sec}s")

    print("\nCaptured Outputs (Snippets):")
    for agent, out in state.get('agent_outputs', {}).items():
        print(f" - {agent}: {out[:175]}...")

    return ans


if __name__ == "__main__":
    # asyncio.run(call_agent_with_observability("Who is satya gautam refer his resume and also show me his skills and experience"))
    # asyncio.run(call_agent_with_observability("Who is satya Nadela ?"))
    asyncio.run(call_agent_with_observability("Who is satya gautam ?"))

async def agentic_app(query:str):
    ans = await call_agent_with_observability(query)
    return ans
